# -*- coding: utf-8 -*-
"""edge_detection_trial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vhx1XOc2AetN9qTDx85YRvaeiW7hIRYN

# New Section
"""

image = imread('puppy.jpeg')
image.shape
feature_matrix = np.zeros((430,760))
feature_matrix.shape
for i in range(0,image.shape[0]):
    for j in range(0,image.shape[1]):
        feature_matrix[i][j] = ((int(image[i,j,0]) + int(image[i,j,1]) + int(image[i,j,2]))/3)
        features = np.reshape(feature_matrix, (430*760))
features.shape

image = imread('puppy.jpeg', -1)
image.shape, imshow(image)

import numpy as np
import cv2 as cv
from matplotlib import pyplot as plt
img = cv.imread('puppy.jpeg',0)
edges = cv.Canny(img,430,760)
plt.subplot(121),plt.imshow(img,cmap = 'gray')
plt.title('Original Image'), plt.xticks([]), plt.yticks([])
plt.subplot(122),plt.imshow(edges,cmap = 'gray')
plt.title('Edge Image'), plt.xticks([]), plt.yticks([])
plt.show()





image= imread('puppy.jpeg')
image.shape

# Commented out IPython magic to ensure Python compatibility.
#importing the required libraries
import numpy as np
from skimage.io import imread, imshow
from skimage.filters import prewitt_h,prewitt_v
import matplotlib.pyplot as plt
# %matplotlib inline

#reading the image
image = imread('puppy.jpeg',as_gray=True)

#calculating horizontal edges using prewitt kernel
edges_prewitt_horizontal = prewitt_h(image)
#calculating vertical edges using prewitt kernel
edges_prewitt_vertical = prewitt_v(image)

imshow(edges_prewitt_vertical, cmap='gray')

# Commented out IPython magic to ensure Python compatibility.
#importing the required libraries
import numpy as np
from skimage.io import imread, imshow
from skimage.filters import prewitt_h,prewitt_v
import matplotlib.pyplot as plt
# %matplotlib inline

#reading the image
image = imread('minho.jpg',as_gray=True)

#calculating horizontal edges using prewitt kernel
edges_prewitt_horizontal = prewitt_h(image)
#calculating vertical edges using prewitt kernel
edges_prewitt_vertical = prewitt_v(image)

imshow(edges_prewitt_vertical, cmap='Dark2')

